### ISSUE TITLE
What version of tensorflow and keras did you use?

### ISSUE THREAD

**Issue by hfingler** [mohofar/CovidCtNet#1]
I'm trying to run your code but none of the versions I've tried worked, could you please share the versions you used? Thanks.

**Comment by mohofar** [comment]
Can you share your error in a file with me? we can solve the issue better. 
my email: mo.homayounfar@gmail.com

**Comment by hfingler** [comment]
It was mostly due to things like tensorflow.compat not being found (if TF was too old) or wrong imports if it was too new.
I ended up figuring it out. The versions below works:

`tensorflow==1.14.0  
keras==2.2.5 
h5py<3.0.0`
